foreach(directory IN LISTS OBJECT_DIRS)
    file(GLOB_RECURSE objects "${directory}/*.o")
    if(NOT objects)
        message(FATAL_ERROR "No first-party objects found in ${directory}")
    endif()
    list(APPEND BINARIES ${objects})
endforeach()
if(NOT BINARIES)
    message(FATAL_ERROR "No objects supplied to the wide-string check")
endif()
execute_process(COMMAND "${NM}" -P -u ${BINARIES}
    RESULT_VARIABLE result OUTPUT_VARIABLE symbols ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Unable to inspect native symbols: ${error}")
endif()
if(symbols MATCHES "(^|\n)_?(wcs|wmem|swprintf|vswprintf|wprintf|wcstombs|mbstowcs|fgetws|swscanf|w8_wcs|w8_swprintf|w8_vswprintf)[^ \n]*[ \t]+U")
    string(REGEX MATCHALL "(^|\n)_?(wcs|wmem|swprintf|vswprintf|wprintf|wcstombs|mbstowcs|fgetws|swscanf|w8_wcs|w8_swprintf|w8_vswprintf)[^ \n]*[ \t]+U[^\n]*" imports "${symbols}")
    message(FATAL_ERROR "First-party module imports host wide-string functions: ${imports}")
endif()
