add_executable(portable_filesystem_test filesystem_test.cpp)
target_link_libraries(portable_filesystem_test PRIVATE wiz8_filesystem)
add_test(NAME portable_filesystem COMMAND portable_filesystem_test)
add_test(NAME portable_default_roots COMMAND portable_filesystem_test default-roots)

add_executable(portable_file_time_test file_time_test.cpp)
target_link_libraries(portable_file_time_test PRIVATE wiz8_filesystem)
add_test(NAME portable_file_time COMMAND portable_file_time_test)
